name: Rename Folder RAUSHAN to GOKU

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  rename_folder_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Rename folder RAUSHAN to GOKU
        run: |
          # Ensure the folder exists before trying to rename it
          if [ -d "RAUSHAN" ]; then
            mv RAUSHAN GOKU
            find . -type f -name "*.py" -exec sed -i 's/RAUSHAN/GOKU/g' {} +
          else
            echo "Folder RAUSHAN does not exist."
          fi

      - name: Commit changes
        run: |
          git config --global user.name 'Gokukhan1'
          git config --global user.email 'Gokukhan1@users.noreply.github.com'
          git add .
          git commit -m "Initial commit " || echo "No changes to commit"
          git push
          
